# Generated by Django 3.2.6 on 2021-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diskusija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('tekst', models.CharField(max_length=2000)),
                ('datum', models.DateTimeField()),
                ('autor', models.CharField(max_length=100)),
                ('vidljivost', models.CharField(choices=[('1', 'Svi korisnici '), ('2', 'Volonteri koji imaju istu oblast interesovanja '), ('3', 'Svi volonteri')], max_length=1)),
            ],
        ),
    ]
