# Generated by Django 3.2.6 on 2021-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskutovanje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StavkaDiskusije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=2000)),
                ('autor', models.CharField(max_length=100)),
                ('vidljivost', models.CharField(choices=[('1', 'Svi korisnici '), ('2', 'Volonteri koji imaju istu oblast interesovanja '), ('3', 'Svi volonteri')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='diskusija',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='diskusija',
            name='tekst',
        ),
        migrations.RemoveField(
            model_name='diskusija',
            name='vidljivost',
        ),
    ]
